import React, { useState } from 'react';
import {
  TrendingUp, ShieldCheck, Award, Zap, Database, BarChart2,
  ChevronRight, CheckCircle2, AlertTriangle, ChevronDown, ChevronUp
} from 'lucide-react';

interface WelcomePageProps {
  onEnter: () => void;
}

const features = [
  {
    icon: <BarChart2 size={28} />,
    title: 'Monte Carlo Forecasting',
    desc: 'Probabilistic revenue simulation across 1,000+ scenarios — not gut-feel guesses. See P10/P50/P90 confidence bands for your quarter.',
    color: '#10b981',
  },
  {
    icon: <ShieldCheck size={28} />,
    title: '6-Signal Risk Engine',
    desc: 'Every deal is scored on stalled activity, stage overage, engagement drop, missing economic buyer, zero-touch, and enterprise exposure.',
    color: '#f59e0b',
  },
  {
    icon: <Award size={28} />,
    title: 'Feature 7 — Holdout Backtest',
    desc: 'Our model vs. rep estimates on real Q1-2026 holdout data. AI beats reps by +33.4 percentage points in win-rate prediction.',
    color: '#6366f1',
  },
  {
    icon: <Database size={28} />,
    title: 'Grounded RAG Citations',
    desc: 'Every recommendation is backed by sourced playbooks — stage recovery scripts, objection handlers, and negotiation templates — not hallucinations.',
    color: '#ec4899',
  },
  {
    icon: <Zap size={28} />,
    title: 'LangGraph Agent Orchestration',
    desc: 'A multi-node stateful agent: Forecast → Risk → Backtest → RAG → Simulate → Narrative. Watch every reasoning step live.',
    color: '#3b82f6',
  },
  {
    icon: <TrendingUp size={28} />,
    title: 'Commit Simulator',
    desc: 'What if we push 5 stalled Enterprise deals? Run what-if scenarios and see projected revenue impact before your Monday call.',
    color: '#14b8a6',
  },
];

const termsText = `
1. ACCEPTANCE OF TERMS
By accessing or using LegitsIQ-AI-Forecast ("the Platform"), you agree to be bound by these Terms and Conditions. If you do not agree, do not use the Platform.

2. PURPOSE & SCOPE
LegitsIQ-AI-Forecast is an AI-powered pipeline revenue forecasting and deal-risk analysis tool designed for sales operations and revenue leadership. All outputs are advisory and probabilistic in nature.

3. DATA USAGE
• All CRM/deal data you upload remains entirely on your local infrastructure. No data is transmitted to third-party servers without explicit consent.
• The AI reasoning engine (when enabled) uses the Groq inference API under Groq's standard terms. If no API key is configured, all processing is fully local.
• Uploaded CSV files are retained in memory for the current session only and are not persisted to disk beyond the application's working directory.

4. ACCURACY DISCLAIMER
Forecasts, risk scores, and recommendations generated by this Platform are statistical models based on historical data patterns. They do not constitute financial advice. Actual sales outcomes may differ materially from model predictions. Past model performance (including the Feature 7 holdout backtest result) does not guarantee future accuracy.

5. INTELLECTUAL PROPERTY
All model logic, agent workflows, RAG knowledge bases, and UI components are proprietary to LegitsIQ. Reverse engineering, redistribution, or commercial resale without written permission is prohibited.

6. LIMITATION OF LIABILITY
The Platform is provided "AS IS." LegitsIQ and its contributors shall not be liable for any direct, indirect, incidental, or consequential damages arising from use of the Platform, including but not limited to lost revenue, missed quotas, or business decisions made based on AI-generated forecasts.

7. PRIVACY
We do not collect personal data beyond what is present in your uploaded deal data. No tracking cookies, analytics SDKs, or third-party telemetry are embedded in this application.

8. MODIFICATIONS
LegitsIQ reserves the right to update these Terms at any time. Continued use of the Platform after updates constitutes acceptance of revised Terms.

9. GOVERNING LAW
These Terms are governed by the laws of your applicable jurisdiction. Any disputes shall be resolved through binding arbitration.

10. CONTACT
For questions about these Terms, reach out to the LegitsIQ team via the project repository.
`;

export default function WelcomePage({ onEnter }: WelcomePageProps) {
  const [showTerms, setShowTerms] = useState(false);
  const [agreed, setAgreed] = useState(false);

  return (
    <div className="welcome-root light-theme">
      {/* ── HEADER ── */}
      <header className="welcome-header">
        <div className="welcome-logo">
          <span className="logo-icon">⚡</span>
          <span className="logo-text">LegitsIQ</span>
          <span className="logo-badge">AI-Forecast</span>
        </div>
        <div className="header-pill">Hackathon Demo · Track D · D4</div>
      </header>

      {/* ── HERO ── */}
      <section className="hero-section">
        <div className="hero-tag">
          <CheckCircle2 size={14} />
          &nbsp;Powered by LangGraph · Monte Carlo · Grounded RAG
        </div>
        <h1 className="hero-title">
          Revenue Forecasting<br />
          <span className="hero-accent">Reimagined with AI</span>
        </h1>
        <p className="hero-sub">
          Stop guessing your quarter. LegitsIQ-AI-Forecast combines probabilistic simulation,
          6-signal deal risk scoring, and a live LangGraph reasoning agent to give your
          revenue team an unfair advantage — every Monday morning.
        </p>
        <div className="hero-stats">
          <div className="stat-pill">
            <span className="stat-num">200+</span>
            <span className="stat-label">Deals Analyzed</span>
          </div>
          <div className="stat-pill">
            <span className="stat-num">+33.4pp</span>
            <span className="stat-label">AI vs Rep Accuracy</span>
          </div>
          <div className="stat-pill">
            <span className="stat-num">6</span>
            <span className="stat-label">Risk Signals</span>
          </div>
          <div className="stat-pill">
            <span className="stat-num">1K+</span>
            <span className="stat-label">Monte Carlo Runs</span>
          </div>
        </div>
      </section>

      {/* ── FEATURES ── */}
      <section className="features-section">
        <h2 className="section-title">Why LegitsIQ-AI-Forecast?</h2>
        <p className="section-sub">
          Built for sales leaders who need certainty, not spreadsheets.
        </p>
        <div className="features-grid">
          {features.map((f) => (
            <div key={f.title} className="feature-card">
              <div className="feature-icon" style={{ color: f.color, background: f.color + '22' }}>
                {f.icon}
              </div>
              <h3 className="feature-title">{f.title}</h3>
              <p className="feature-desc">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* ── HOW IT WORKS ── */}
      <section className="flow-section">
        <h2 className="section-title">How the Agent Works</h2>
        <div className="flow-steps">
          {[
            { step: '01', label: 'Upload Deals CSV', detail: 'Drop your CRM export' },
            { step: '02', label: 'Agent Activates', detail: 'LangGraph orchestrates 6 nodes' },
            { step: '03', label: 'Risk Scored', detail: '6 signals per deal, ranked' },
            { step: '04', label: 'Forecast Built', detail: 'Monte Carlo P10/P50/P90' },
            { step: '05', label: 'RAG Cites Sources', detail: 'Playbooks grounded in data' },
            { step: '06', label: 'Monday Briefing', detail: 'CRO-ready narrative output' },
          ].map((s, i) => (
            <React.Fragment key={s.step}>
              <div className="flow-step">
                <div className="flow-num">{s.step}</div>
                <div className="flow-label">{s.label}</div>
                <div className="flow-detail">{s.detail}</div>
              </div>
              {i < 5 && <ChevronRight size={20} className="flow-arrow" />}
            </React.Fragment>
          ))}
        </div>
      </section>

      {/* ── TERMS ── */}
      <section className="terms-section">
        <button
          className="terms-toggle"
          onClick={() => setShowTerms(!showTerms)}
        >
          <span>Terms &amp; Conditions</span>
          {showTerms ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
        </button>

        {showTerms && (
          <div className="terms-body">
            <pre className="terms-text">{termsText.trim()}</pre>
          </div>
        )}

        <label className="terms-agree">
          <input
            type="checkbox"
            checked={agreed}
            onChange={(e) => setAgreed(e.target.checked)}
          />
          <span>
            I have read and agree to the{' '}
            <button className="terms-link" onClick={() => setShowTerms(true)}>
              Terms &amp; Conditions
            </button>
          </span>
        </label>
      </section>

      {/* ── CTA ── */}
      <section className="cta-section">
        <button
          className={`enter-btn ${agreed ? 'enter-btn-active' : 'enter-btn-disabled'}`}
          onClick={agreed ? onEnter : undefined}
          disabled={!agreed}
          title={!agreed ? 'Please agree to the Terms & Conditions first' : ''}
        >
          Enter the Platform &nbsp;→
        </button>
        {!agreed && (
          <p className="cta-hint">
            <AlertTriangle size={13} /> &nbsp;Please accept the Terms &amp; Conditions to proceed
          </p>
        )}
      </section>

      {/* ── FOOTER ── */}
      <footer className="welcome-footer">
        <span>© 2026 LegitsIQ · AI-Forecast Platform · Track D — Pipeline Revenue Forecasting &amp; Deal-Risk Agent</span>
      </footer>
    </div>
  );
}
